language: java
jdk:
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - .gradle
env:
  global:
    - secure: AuWZ1nkrl2ORtguiZ0VPToo3T+X+JpNqMAvC9mQePFGFeZNILW7S4TicgQL0T41ElFumJbNf/sAV+gbomeLjecii2lAKPlcSrRNVZiYnnEmRiDi4EvjLvWS1fqdau3Deb9jZc2WYZN2wBQfHlT9TvpgcGtqDjjD8TLSTGJLRYDLQP8QS7BsmQhcZv0jLjEO9vfi7puiq1XGmK3+dzydXnPx3SGG4k6KlSNIaw9AZqUlLvA8MHl533WxM2pN6ate86RV1WsuZ8YxZxsOApVTS4Kw+CMJq9Jdra2UdgjdPgxYj6S9TeUCA/lsNS6JlkEy+bimo9lXl2HriSItBVfw0TOz7u29ww8qDafKe5tAtGr/Q0Bxjy8lq49GMp1FhKzsdQXYHVWOmTDLrdq1agkT6iKJ2UZzoyLnWtvo4TiTlc7LfyMzIHmF95CcF1WXTDyKE7u7Co/vn4JP3i2GYLR5QlAvRTZDtufKrQQq01BKJfIpr5kYU+QDyyKj9JzDRGEcxdYYkPmmd2NWDYl2TDbXyxo1RrCdfScxLEYEMoc9KlxfLWaACkaKa6/YcV9QAImZhMZ6wPteGk2HW0kmN1eOUt6JSPLPLGEDzQWzvtaOmo/mEz9uhJyST1A/aAOSm9sTkkFFVbAxDUa73GcjjzcidwBREPbA6mqcXMJKoKIFhZ+4=
    - secure: OR7u1Kws3r4cBlfF6TaDhRzKjlj9D23rJ4OzovPAz+CndYwUPdED6+AIpF6jPC0B4CPGyF+m0dmDuyqeof+nuQrCja5CsLgXXf0xcDvIz/WM/S5SXse0oT90krVUGk1Uxmx+wHE9KmM5xo0nhxwDZk6BYqqmCtB0S+WrEy0JMkhrizzELHO7W2TGwI28JykmBgfa0i42Dy1D5Z9WUMu4OO1EPyc/rEbLDWAxu7QEh4rYRDnhrkij78zEndxE8B33c1cStGpjcIPpoRa36z4kI39qq0FCYQW0g6cjPpQ8cwokggf6FWHQNN2edJMQJGC/DVXmGzGjuSc8M32Kkz1QSofCEnq2S9+nqXek0PAL/mx4wPWXujTa8QHCLZoYB9GAsjOr6glxsendlkHtNnVsTtJThiCgT2mjQdqFwslOjPbmO6Ys1gUJ3zTDxLVKX1VlpbwFoH7r5B8xTb+PcM+MMW+4ryPM2u5lSu/Q0khPE7shz110wk8bbjtvo+2K1q1fK/P3QAZAD5v3088C3YFZKUWGXPnfIFO+BNytABn3Q49F/oIy3ewJMIOdtc99zj/taZrsOpEgSuuON0vwPjSJINStQu6CcWBJApgLjVWobnqoB/MeeonddYCBoDfSh/L8W7BtnfPcZGFrUB1hxlr9s41I7oxykdQZrbYByiWGHb0=
    - secure: h9TcFgNAL+ElGuaT2N+b4syK+pkD3jlqns8GpFMVFD644wxvLUWZiya+41xIxUWIT7elQz5th8v4JnYAEfI8cOGDgIKpd7I70EUoTOWtA+oSATASDi28VK+Me4I8w8Bl7of3mpScmXCYOGxrWBJbs4ZEapzAjArk0t9O6XRpKGdPRJyanijFz5x4jAkFcwIPmmytcWb/nphxnBXPRZcdERC0fQBFyegtQ/YKvZ0BSv80G2S4+Rkr4PEe0lKW5qL0eVZLBQi1chGFwAUYmFkwt+yee/iUkyyZefHkC0TJVazLKNNtmCVFg9picwGW9uGQhlb86vaAvjBhmNM5p5vA3KR4/jgZzyeRqzfOKQ9f5czEv/V4lRYi+978B8USS0Lov4kEdqRlp5DfmqX7orDCvJXcFIYySvKXlTnry4/qEduvk8a2u1a+m+pkzB85HJ+gA+fUZZMxPNUyxIU/HLz2VkRDCb3UIw1vDe14BuNFBPNeN+JUJwLEAVxKetzb2SadsS1jA2Zmibf7TwhN2URGm32eTG4Rp3tKeo3xKii0v+6KHW8gkMLIBBiOimy5ko+rWfOuSEkSQ7UzQIri/9KktAcl8lrCa8s/FCcnx+nBuFrF5Bf+rwX3U3Asp27hdS2NasHRUHF2KWjZupglMmDSoRdzFaW2KvFV2aN6GQuUT9A=
install: true
script:
  - ./gradlew printEnv
  
